version: 0.2

env:
  variables:
    FUNCTION_NAME: "cicd-demo-deploy"
    ZIP_FILE: lambda.zip

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - echo "Creating zip archive"
      - yum install zip -y
      - echo ${FUNCTION_NAME}
      - echo ${ZIP_FILE}
  build:
    commands:
      - echo preparing zip archive
      - zip -r $ZIP_FILE .
      - echo "deploy lambda function"
      - aws lambda update-function-code --function-name  ${FUNCTION_NAME} --zip-file fileb://${ZIP_FILE}
