version: 0.2

env:
  variables:
    FUNCTION_NAME: "cicd-demo-deploy"
    ZIP_FILE: lambda.zip
  parameter-store:
    CHAT_ID: CHAT_ID
    BOT_TOKEN: bot_token

phases:
  build:
    commands:
      - echo "Chat ID ${CHAT_ID}, ${BOT_TOKEN}"
      - aws lambda invoke --function-name ${FUNCTION_NAME} --cli-binary-format raw-in-base64-out --payload '{"key":"value"}' response.json
    finally:
      - |
        WEBHOOK_URL="https://api.telegram.org/bot${BOT_TOKEN}/sendMessage"
        STATUS="Success"
        if [ "$CODEBUILD_BUILD_SUCCEEDING" -ne 1 ]; then
          STATUS="Failed"
        fi

        MESSAGE="🔔 Build status: *${STATUS}*\nBuild ID: \`${CODEBUILD_BUILD_ID}\`"

        PAYLOAD=$(cat <<EOF
        {
          "chat_id": "${CHAT_ID}",
          "text": "${MESSAGE}",
          "parse_mode": "Markdown"
        }
        EOF
        )

        curl -s -X POST "${WEBHOOK_URL}" -H "Content-Type: application/json" -d "${PAYLOAD}"
